lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
    pass_phrase: '%env(JWT_PASSPHRASE)%' # required for token creation
    token_ttl: 3600 # in seconds, default is 3600

    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization

        # check token in a cookie
        cookie:
            enabled: true
            name: BEARER

        # check token in query string parameter
        query_parameter:
            enabled: false
            name: bearer

        # check token in a cookie
        split_cookie:
            enabled: false
            cookies:
                - jwt_hp
                - jwt_s
    set_cookies:
        BEARER: ~

    # remove the token from the response body when using cookies
    remove_token_from_body_when_cookies_used: false